environment:
  BABEL_ENV: "test"
  matrix:
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

before_test:
  - yarn run build

test_script:
  - yarn run test-only

build: off
